import React, { useState } from "react";
import {
  ChevronDown,
  ChevronUp,
  Shield,
  AlertTriangle,
  Book,
  Lock,
  RefreshCw,
  Award,
  Users,
  Calendar,
  FileText,
} from "lucide-react";

const CustomAlert = ({ title, description }: any) => (
  <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
    <div className="flex items-center gap-2">
      <AlertTriangle className="w-5 h-5 text-blue-800 dark:text-blue-200" />
      <h3 className="text-lg font-semibold text-blue-800 dark:text-blue-200">
        {title}
      </h3>
    </div>
    <p className="mt-2 text-blue-700 dark:text-blue-300">{description}</p>
  </div>
);

export const ComprehensivePolicy = () => {
  const [expandedSection, setExpandedSection] = useState<string | null>(null);

  const policySections = [
    {
      id: "introduction",
      title: "Introduction",
      icon: <Book className="w-5 h-5" />,
      content: `This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.

Last updated: February 23, 2025`,
    },
    {
      id: "definitions",
      title: "Interpretation and Definitions",
      icon: <FileText className="w-5 h-5" />,
      content: `Interpretation
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

Definitions
For the purposes of this Privacy Policy:

• Account means a unique account created for You to access our Service or parts of our Service.
• Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
• Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to BlueKites, Rabindra Sarani Main Road, Siliguri 734006, West Bengal, IN.
• Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
• Country refers to: West Bengal, India
• Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
• Personal Data is any information that relates to an identified or identifiable individual.
• Service refers to the Website.
• Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
• Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
• Website refers to BlueKites, accessible from https://www.bluekites.org
• You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.`,
    },
    {
      id: "data-collection",
      title: "Collecting and Using Your Personal Data",
      icon: <Lock className="w-5 h-5" />,
      content: `Types of Data Collected

Personal Data
While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
• Email address
• First name and last name
• Phone number
• Address, State, Province, ZIP/Postal code, City
• Usage Data

Usage Data
Usage Data is collected automatically when using the Service.
Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.

We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.`,
    },
    {
      id: "cookies",
      title: "Tracking Technologies and Cookies",
      icon: <RefreshCw className="w-5 h-5" />,
      content: `We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:

• Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
• Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).

Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on TermsFeed website article.

We use both Session and Persistent Cookies for the purposes set out below:

Necessary / Essential Cookies
Type: Session Cookies
Administered by: Us
Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.

Cookies Policy / Notice Acceptance Cookies
Type: Persistent Cookies
Administered by: Us
Purpose: These Cookies identify if users have accepted the use of cookies on the Website.

Functionality Cookies
Type: Persistent Cookies
Administered by: Us
Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.

For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.`,
    },
    {
      id: "data-usage",
      title: "Use of Your Personal Data",
      icon: <Shield className="w-5 h-5" />,
      content: `The Company may use Personal Data for the following purposes:

• To provide and maintain our Service, including to monitor the usage of our Service.
• To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
• For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
• To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
• To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
• To manage Your requests: To attend and manage Your requests to Us.
• For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
• For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.

We may share Your personal information in the following situations:

• With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
• For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
• With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
• With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.
• With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
• With Your consent: We may disclose Your personal information for any other purpose with Your consent.`,
    },
    {
      id: "data-retention",
      title: "Retention of Your Personal Data",
      icon: <Calendar className="w-5 h-5" />,
      content: `The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.

The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.`,
    },
    {
      id: "data-transfer",
      title: "Transfer of Your Personal Data",
      icon: <RefreshCw className="w-5 h-5" />,
      content: `Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.

Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.

The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.`,
    },
    {
      id: "delete-data",
      title: "Delete Your Personal Data",
      icon: <Lock className="w-5 h-5" />,
      content: `You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.

Our Service may give You the ability to delete certain information about You from within the Service.

You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.

Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.`,
    },
    {
      id: "data-disclosure",
      title: "Disclosure of Your Personal Data",
      icon: <Shield className="w-5 h-5" />,
      content: `Business Transactions
If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.

Law enforcement
Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).

Other legal requirements
The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
• Comply with a legal obligation
• Protect and defend the rights or property of the Company
• Prevent or investigate possible wrongdoing in connection with the Service
• Protect the personal safety of Users of the Service or the public
• Protect against legal liability`,
    },
    {
      id: "data-security",
      title: "Security of Your Personal Data",
      icon: <Lock className="w-5 h-5" />,
      content: `The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.`,
    },
    {
      id: "children-privacy",
      title: "Children's Privacy",
      icon: <Users className="w-5 h-5" />,
      content: `Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.

If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.`,
    },
    {
      id: "other-links",
      title: "Links to Other Websites",
      icon: <FileText className="w-5 h-5" />,
      content: `Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.`,
    },
    {
      id: "policy-updates",
      title: "Changes to this Privacy Policy",
      icon: <RefreshCw className="w-5 h-5" />,
      content: `We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.

We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.`,
    },
    {
      id: "refunds",
      title: "Refund Policy",
      icon: <Shield className="w-5 h-5" />,
      content: `Students are entitled to a full refund if they decide to leave a course within 7 days of enrollment, regardless of the reason. If a student withdraws after 7 days but before the course concludes, they will receive a 20% refund of the total course fee, and the remaining 80% will be retained by Blue Kites to cover administrative and resource costs.`,
    },
    {
      id: "certificates",
      title: "Certification Requirements",
      icon: <Award className="w-5 h-5" />,
      content: `Students who withdraw from a course without completing the full curriculum will not be eligible to receive a certificate of completion. Certificates are awarded only to students who successfully finish the course as per the set criteria.`,
    },
    {
      id: "instructors",
      title: "Instructor Changes",
      icon: <Users className="w-5 h-5" />,
      content: `Teachers may be replaced during the course of a program due to scheduling, availability, or performance reasons. We expect our users to cooperate and adapt to these changes, as our goal is to provide the best possible learning experience with qualified instructors.`,
    },
    {
      id: "subscription",
      title: "Subscription Benefits",
      icon: <Calendar className="w-5 h-5" />,
      content: `Users who enroll in our annual subscription package will receive an additional one month of free access as a bonus. This incentive is designed to reward long-term commitment and provide added value to our dedicated users.`,
    },
    {
      id: "courses",
      title: "Course Availability",
      icon: <Book className="w-5 h-5" />,
      content: `Courses with low enrollment or demand may be temporarily removed from our platform and replaced with other courses that better suit our users' interests. This ensures that we continue offering high-quality and relevant content for the majority of learners.`,
    },
    {
      id: "piracy",
      title: "Content Protection",
      icon: <Shield className="w-5 h-5" />,
      content: `Any user found engaging in piracy or illegal distribution of our content will face severe consequences. This includes a permanent suspension from the platform and potential legal action. We are dedicated to protecting our intellectual property and maintaining the integrity of our services.`,
    },
    {
      id: "contact",
      title: "Contact Us",
      icon: <Users className="w-5 h-5" />,
      content: `If you have any questions about this Privacy Policy, You can contact us:

• By email: bluekites162@gmail.com
• By phone number: +91-7029864675`,
    },
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 py-12 pt-[150px]">
      {/* Header Section */}
      <div className="mb-8">
        <h1 className="text-3xl md:text-4xl font-bold text-black dark:text-white mb-4">
          BlueKites Platform Policies
        </h1>
        <CustomAlert
          title="Important Notice"
          description="Please review our privacy policy and terms and conditions carefully. By using our platform, you agree to these policies."
        />
      </div>

      {/* Policy Sections */}
      <div className="space-y-4">
        {policySections.map((policy) => (
          <div
            key={policy.id}
            className="border dark:border-gray-700 rounded-lg overflow-hidden bg-white dark:bg-gray-800"
          >
            <button
              onClick={() =>
                setExpandedSection(
                  expandedSection === policy.id ? null : policy.id
                )
              }
              className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors"
            >
              <div className="flex items-center space-x-3">
                {policy.icon}
                <h2 className="text-lg font-semibold text-black dark:text-white">
                  {policy.title}
                </h2>
              </div>
              {expandedSection === policy.id ? (
                <ChevronUp className="w-5 h-5 text-gray-500" />
              ) : (
                <ChevronDown className="w-5 h-5 text-gray-500" />
              )}
            </button>

            {expandedSection === policy.id && (
              <div className="px-6 py-4 border-t dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
                <div className="text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-line">
                  {policy.content}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Footer Note */}
      <div className="mt-8 text-center text-sm text-gray-600 dark:text-gray-400">
        Last updated: February 2025. These terms are subject to change. Please
        check regularly for updates.
      </div>
    </div>
  );
};

export default ComprehensivePolicy;
